// AUTO-GENERATED by scripts/stamp-version.mjs — do not edit by hand.
export const APP_VERSION = "2.3.10";
export const APP_BUILD_SHA = "3cc1111";
export const APP_BUILD_DIRTY = true;
export const APP_BUILD_DATE = "2026-05-18T21:41:12.547Z";
